# Header

menu:
  主页: /
  # 随笔: /tags/随笔/
  # 游记: /tags/游记/


# SubNav
subnav:
  github: "https://github.com/BestDingSheng"
  weibo: "https://juejin.im/timeline"
  zhihu: "https://www.zhihu.com/"
  #qq: "#"
  # weixin: "#"
  jianshu: "http://www.jianshu.com/"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  mail: "mailto:727040141@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content

# 文章太长，截断按钮文字
#excerpt_link: more
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 请在需要打赏的文章的md文件头部，设置属性reward: true

# 打赏基础设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '支持原创是对你我最大的支持- -。'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /uploads/alipay-reward-image.jpg
# 微信二维码图片地址
weixin: /uploads/wechatPay.jpg

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /favicon.ico

#你的头像url
avatar: /uploads/touxiang.png

#是否开启分享
share_jia: true

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论

duoshuo: true
duoshuo_info:
  ua_enable: true
  admin_enable: true
  user_id: 6345218763687724000
  admin_nickname: 岁月如歌



# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  # header: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'
  header: 'transparent'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友情链接'
  aboutme: '关于我'

friends:
  掘金: https://juejin.im/welcome 
  vu2x: https://www.v2ex.com/
  vue中文网: https://cn.vuejs.org/v2/guide/
  myProject: https://github.com/BestDingSheng/Learn-and-Share
  Mac破解软件: http://xclient.info/
  CNode中文社区: https://cnodejs.org/  

aboutme: 看得懂的，都不是命运。<br>说得清的，都不叫爱情。<br>忘得了的，都不是遗憾。<br>听得见的，都不是伤心。<br>躲得开的，都不是缘分。<br>猜得透的，都不叫人生。